/*

 POOL_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 30 x 18
   Tile set      : Z:\home\jorringe\DoggyPaddle\tiles\pool_8x8.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define poolMapWidth 30
#define poolMapHeight 18
#define poolMapBank 0

extern unsigned char poolMap[];

/* End of POOL_MAP.H */
