/*

 TEXT.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 10 x 1
   Tile set      : Z:\home\danielagbay\workspace\hackathon\DoggyPaddle\tiles\text.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define textMapWidth 10
#define textMapHeight 1
#define textMapBank 0

unsigned char textMap[] =
{
  0x00,0x01,0x02,0x03,0x04,0x06,0x05,0x03,0x07,0x08
};

/* End of TEXT.C */
