/*

 TEXT.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 10 x 1
   Tile set      : Z:\home\danielagbay\workspace\hackathon\DoggyPaddle\tiles\text.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define textMapWidth 10
#define textMapHeight 1
#define textMapBank 0

extern unsigned char textMap[];

/* End of TEXT.H */
